language: node_js
dist: focal
sudo: false
cache:
  apt: true
  directories:
    - node_modules

node_js: node

install:
  - npm install -D
  
scripts:
  - npm run cover

deploy:
  provider: npm
  email: alberteinstein007@126.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true